name: Build APP

on:
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APP Streamlit Docker image
        run: |
          echo "Build APP"
          docker build \
            -t app:${{ github.sha }} \
            ./services/app

